### PR TITLE
Create the hyperlight proposal process

### PR DESCRIPTION
**Pull request by devigned**
This pull request establishes the Hyperlight Improvement Proposal process, or HIP. This process is roughly modeled after the Kubernetes Enhancement Proposal process, or KEP.

In this PR, I introduce the first proposal, which is the proposal for the proposal process. The documentation around the proposal process is provided as well as a template to help folks get started.

### CODE REVIEW

**Review by danbugs — COMMENTED** [review]
Looking good. Might just be worth adding a section on what the process for submitting a HIP looks like.

(1) Write a HIP.
(2) Make a PR with a HIP.
(3) Address feedback on the HIP.

After that, if the HIP gets merged, is the idea that it was approved for implementation? I think we should clarify that in writing.

**Comment by devigned** [comment]
@danbugs, does this section cover it adequately (https://github.com/hyperlight-dev/hyperlight/pull/25/files#diff-38d0e78b0aa3c1b0361bb75e9c4ecbcf6d356dc01ac993966a562ce14252320eR8-R24). I'm guessing not since it wasn't clear. WDYT?

**Comment by danbugs** [comment]
> @danbugs, does this section cover it adequately (https://github.com/hyperlight-dev/hyperlight/pull/25/files#diff-38d0e78b0aa3c1b0361bb75e9c4ecbcf6d356dc01ac993966a562ce14252320eR8-R24). I'm guessing not since it wasn't clear. WDYT?

No, I just missed that on my review 😅 —LGTM!

**Review by danbugs — APPROVED** [review]

**Review by dblnz — APPROVED** [review]
LGTM

**Pull request merged**
