### PR TITLE
docs: fix typo 

### PR DESCRIPTION
**Pull request by samrose**

### CODE REVIEW

**Comment by jprendes** [comment]
Hi! Thanks again for the contribution!
Would you mind following the instructions [here](https://github.com/hyperlight-dev/hyperlight/pull/43/checks?check_run_id=32710217694) to get the DCO step passing?

**Comment by samrose** [comment]
@jprendes there you go LOL

**Review by jprendes — APPROVED** [review]

**Review by dblnz — APPROVED** [review]

**Comment by jprendes** [comment]
Sorry, would you mind also signing your commit?
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by samrose** [comment]
@jprendes there you go! ^^

**Review by devigned — APPROVED** [review]
lgtm! Thank you.

**Pull request merged**
