### PR TITLE
Fix README links

### PR DESCRIPTION
**Pull request by kk-src**
Fix the README links in "For developers" section to append .md file extension. 
Fixes issue #59

### CODE REVIEW

**Comment by jprendes** [comment]
Thanks @kk-src !
Would you mind signing off and signing your commit? Thanks!

**Comment by kk-src** [comment]
> Thanks @kk-src ! Would you mind signing off ~and signing~ (looks like it's already signed) your commit? Thanks!

Added the Signed-off-by to the commit message.

**Review by jprendes — APPROVED** [review]
LGTM,
Thanks @kk-src !

**Review by simongdavies — APPROVED** [review]

**Comment by ludfjig** [comment]
Looks like the commit is not signed @kk-src , maybe it got unsigned when you added the sign-off ?

**Comment by jprendes** [comment]
Thanks @kk-src !

**Pull request merged**
