### PR TITLE
[chore] Add devcontainer config

### PR DESCRIPTION
**Pull request by dblnz**
This adds devcontainer config to be used with codespaces and Visual Studio

### CODE REVIEW

**Comment by danbugs** [comment]
Is this possible now? I tried doing this about 2 years ago and, iirc, it wasn't possible to access `/dev/kvm`.

**Comment by dblnz** [comment]
> Is this possible now? I tried doing this about 2 years ago and, iirc, it wasn't possible to access `/dev/kvm`.

I ran some tests locally and it seems to be working.

**Comment by danbugs** [comment]
> > Is this possible now? I tried doing this about 2 years ago and, iirc, it wasn't possible to access `/dev/kvm`.
> 
> I ran some tests locally and it seems to be working.

Awesome! Might just not work if people try to use it from the browser? We can add a note on that after testing, though.

**Comment by dblnz** [comment]
> > > Is this possible now? I tried doing this about 2 years ago and, iirc, it wasn't possible to access `/dev/kvm`.
> 
> > 
> 
> > I ran some tests locally and it seems to be working.
> 
> 
> 
> Awesome! Might just not work if people try to use it from the browser? We can add a note on that after testing, though.

I ran a couple of times today in the browser, but the issue was it built the container image too slowly and I believe it got terminated due to timeout.
Now I am looking into how to make the container smaller so that it is built faster

**Comment by devigned** [comment]
@dblnz have you considered building a base image and then using that rather than base Debian?

**Comment by dblnz** [comment]
> @dblnz have you considered building a base image and then using that rather than base Debian?

Yes, and that is the current plan, after I test locally and see everything works, then I'll push the image so it can be used with devcontainers

**Pull request closed without merging**
